/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package no11;

/**
 *
 * @author win11
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textChiper = new javax.swing.JTextField();
        textPlain = new javax.swing.JTextField();
        caisarEncript = new javax.swing.JButton();
        caisarDecript = new javax.swing.JButton();
        caisarClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textKey = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textPlain2 = new javax.swing.JTextField();
        vigenereEncript = new javax.swing.JButton();
        textCipher2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vigenereDecript = new javax.swing.JButton();
        textKey2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vigenereClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(502, 40));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel1.setText("CAISAR CIPHER");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("PLAIN TEXT");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("CIPHER TEXT");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        textChiper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChiperActionPerformed(evt);
            }
        });
        jPanel4.add(textChiper, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, -1));

        textPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlainActionPerformed(evt);
            }
        });
        jPanel4.add(textPlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));

        caisarEncript.setText("ENCRIPT");
        caisarEncript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caisarEncriptActionPerformed(evt);
            }
        });
        jPanel4.add(caisarEncript, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        caisarDecript.setText("DECRIPT");
        caisarDecript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caisarDecriptActionPerformed(evt);
            }
        });
        jPanel4.add(caisarDecript, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        caisarClear.setText("CLEAR");
        caisarClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caisarClearActionPerformed(evt);
            }
        });
        jPanel4.add(caisarClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel4.setText("KEY");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        textKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKeyActionPerformed(evt);
            }
        });
        jPanel4.add(textKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, -1));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(502, 40));

        jLabel5.setFont(new java.awt.Font("YouYuan", 0, 24)); // NOI18N
        jLabel5.setText("VIGENERE CIPHER");
        jPanel5.add(jLabel5);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setText("PLAIN TEXT");

        vigenereEncript.setText("ENCRIPT");
        vigenereEncript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenereEncriptActionPerformed(evt);
            }
        });

        jLabel7.setText("CIPHER TEXT");

        vigenereDecript.setText("DECRIPT");
        vigenereDecript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenereDecriptActionPerformed(evt);
            }
        });

        jLabel8.setText("KEY");

        vigenereClear.setText("CLEAR");
        vigenereClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenereClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textKey2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(textCipher2)
                    .addComponent(textPlain2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vigenereEncript)
                    .addComponent(vigenereDecript))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vigenereClear)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPlain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vigenereEncript))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCipher2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(vigenereDecript))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(vigenereClear)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textChiperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChiperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textChiperActionPerformed

    private void textPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlainActionPerformed

    private void caisarDecriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caisarDecriptActionPerformed
        String encript = textChiper.getText().toLowerCase();
        int key = Integer.parseInt(textKey.getText());
        String plainText = caisarDecript(encript, key);
        textPlain.setText(plainText.toUpperCase());
    }//GEN-LAST:event_caisarDecriptActionPerformed

    private void caisarEncriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caisarEncriptActionPerformed
        String plainText = textPlain.getText().toLowerCase();
        int key = Integer.parseInt(textKey.getText());
        String encript = caisarEncript(plainText, key);
        textChiper.setText(encript.toUpperCase());
    }//GEN-LAST:event_caisarEncriptActionPerformed

    private void caisarClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caisarClearActionPerformed
        textPlain.setText("");
        textChiper.setText("");
        textKey.setText("");
    }//GEN-LAST:event_caisarClearActionPerformed

    private void textKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKeyActionPerformed

    private void vigenereEncriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenereEncriptActionPerformed
        String plainText = textPlain2.getText().toLowerCase();
        String key = textKey2.getText().toLowerCase();
        String encript = vigenereEncript(plainText, key);
        textCipher2.setText(encript.toUpperCase());
        
    }//GEN-LAST:event_vigenereEncriptActionPerformed

    private void vigenereDecriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenereDecriptActionPerformed
        String encript = textCipher2.getText().toLowerCase();
        String key = textKey2.getText().toLowerCase();
        String plainText = vigenereDecript(encript, key);
        
        textPlain2.setText(plainText.toUpperCase());
    }//GEN-LAST:event_vigenereDecriptActionPerformed

    private void vigenereClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenereClearActionPerformed
        textPlain2.setText("");
        textCipher2.setText("");
        textKey2.setText("");
    }//GEN-LAST:event_vigenereClearActionPerformed

    /**
     * @param args the command line arguments
     */
    private static String caisarEncript(String text, int shift){
        StringBuffer sb = new StringBuffer();
        
        for (int i = 0; i < text.length(); i++) {
            int p = text.charAt(i) - 97;
            int e = (p+shift) % 26;
            char kembaliHuruf = (char)(e+97);
            sb.append(kembaliHuruf);
        }
        return sb.toString();
    }
    private static String caisarDecript(String text, int shift){
        StringBuffer sb = new StringBuffer();
        
        for (int i = 0; i < text.length(); i++) {
            int e = text.charAt(i) - 97;
            int p = (e - shift) % 26;
            if (p < 0) {
                p +=26;
            }
            char kembaliAngka = (char)(p + 97);  
            sb.append(kembaliAngka);
        }
        return sb.toString();
    }
    private static String vigenereEncript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        
        int panjang = text.length();
        
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();
            int k = (int) shift.charAt(j) - 97;
            int p = (int) text.charAt(i) - 97;
            int e = (p + k) % 26;
            char kembaliHuruf = (char)(e+97);
            sb.append(kembaliHuruf);  
        }
        return sb.toString();
    }
    private static String vigenereDecript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        
        int panjang = text.length();
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();
            int k = (int) shift.charAt(j) - 97;
            int p = (int) text.charAt(i) - 97;
            int e = (p - k) % 26;
            
            if (e < 0) {
                e += 26;  
            }
            char kembaliHuruf = (char)(e+97);
            sb.append(kembaliHuruf);               
        }
        return sb.toString();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caisarClear;
    private javax.swing.JButton caisarDecript;
    private javax.swing.JButton caisarEncript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField textChiper;
    private javax.swing.JTextField textCipher2;
    private javax.swing.JTextField textKey;
    private javax.swing.JTextField textKey2;
    private javax.swing.JTextField textPlain;
    private javax.swing.JTextField textPlain2;
    private javax.swing.JButton vigenereClear;
    private javax.swing.JButton vigenereDecript;
    private javax.swing.JButton vigenereEncript;
    // End of variables declaration//GEN-END:variables
}
